services:
  pdfsearch:
    build: .
    container_name: pdfsearch
    volumes:
      - ./pdfs:/app/pdfs
      - ./test:/app/test
      - ./db:/app/db
      - ./found_pdfs:/app/found_pdfs
    stdin_open: true
    tty: true
